# -----------------------------------------------------------------------------
# Config definition
# -----------------------------------------------------------------------------
MODEL:
  # 使用 cuda 或 cpu
  DEVICE: "cuda"
  # GPU 的 ID 号
  DEVICE_ID: '0'
  # 主干网络名称
  NAME: 'resnet50_ibn_a'
  # 主干网络的最后一个步长
  LAST_STRIDE: 1
  # 预训练模型路径
  PRETRAIN_PATH: ''
  # BNNeck 的配置
  NECK: 'bnneck'

# -----------------------------------------------------------------------------
# INPUT
# -----------------------------------------------------------------------------
INPUT:
  # 测试图像的尺寸
  SIZE_TEST: [256, 128]
  # 图像归一化的均值
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  # 图像归一化的标准差
  PIXEL_STD: [0.229, 0.224, 0.225]
  # 填充尺寸
  PADDING: 10

# -----------------------------------------------------------------------------
# Dataset
# -----------------------------------------------------------------------------
DATASETS:
  # 数据集名称列表
  NAMES: ['market1501']
  # 数据集根目录
  ROOT_DIR: 'query'

# -----------------------------------------------------------------------------
# DataLoader
# -----------------------------------------------------------------------------
DATALOADER:
  # 数据加载线程数
  NUM_WORKERS: 4

# -----------------------------------------------------------------------------
# TEST
# -----------------------------------------------------------------------------
TEST:
  # 测试时每个批次的图像数
  IMS_PER_BATCH: 128
  # 是否使用重排 (re-ranking)
  RE_RANKING: 'no'
  # 已训练模型的权重路径
  WEIGHT: "weights/ReID_resnet50_ibn_a.pth"
  # 测试时使用的 BNNeck 特征
  NECK_FEAT: 'after'
  # 测试前是否对特征进行归一化
  FEAT_NORM: 'yes'

# ---------------------------------------------------------------------------- #
# Misc options
# ---------------------------------------------------------------------------- #
# 检查点和日志的输出目录
OUTPUT_DIR: ""